# Generated by Django 6.0.7 on 2026-08-20 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isDeliversd',
            new_name='isDelivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippihgPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxtPrice',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippihgPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='shippingPrice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='taxPrice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shippingPrice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
